# WhatATheme
markdown: kramdown

# URL of the Site
url: ''
# Base URL of the Site (i.e., Name of the Repository in which the Site is hosted)
baseurl: 

# Title of the Site
title: Andrea Fox
# Description of the Site
description: Data Science Project Portfolio
# URL of Image of the Site
site-image: /WhatATheme/assets/images/meta.jpg
# Keywords of the Site
site-keywords: Site, Template, Theme
# URL for the Image of custom Favicon
favicon-url: 

# URL of the Image of Custom Hero Image (i.e., the image in the background of the very first section of the Homepage)
heroimage: https://raw.githubusercontent.com/anfox86/anfox86.github.io/master/assets/images/KC_skyline.jpg

# Social Media and Contact
# If you don't want to use any icon, you can leave them blank.
email: andrea.fox26@outlook.com
facebook_username: 
twitter_username: @brokenfox26
instagram_username: 
linkedin_username: www.linkedin.com/in/andrea-fox86
github_username:  anfox86
youtube_channel_id: 


# Google Analytics
google-analytics: UA-163806439-1

# Disqus
disqus-shortname: Andrea

# Name of the Author
author-name: Andrea Fox
# URL for the Image of the Author
author-image: assets/images/profile_pic.jpg
# 60 Words About the Author
author-about: I am completing my Masters of Science in Data Science at Bellevue University. I currently work for Cerner, a healthcare software company, specifically creating the standard for how clients should use our Patient Accounting solutions.
# URL to the Author's Profile (i.e., Github, Twitter, Stackoverflow, etc)
author-url: https://github.com/anfox86

# SASS
sass:
  sass_dir: _sass
  style: compressed

# Build settings
plugins:
  - jekyll-admin
  - jekyll-feed

# Permalink
permalink: "blog/:title"

# Compress
compress_html:
  clippings: all

# Defaults
defaults:
  -
    scope:
      type: 'posts'
    values:
      layout: post
      post-image: ""
      description: ""
      tags:
        - ""
  -
    scope:
      type: 'pages'
    values:
      layout: page

# Exclude
exclude:
  - .sass-cache/
  - .jekyll-cache/
  - gemfiles/
  - Gemfile
  - Gemfile.lock
  - node_modules/
  - vendor/bundle/
  - vendor/cache/
  - vendor/gems/
  - vendor/ruby/
